use_frameworks!

target 'OperatorExtensions_Example' do
  pod 'OperatorExtensions', :path => '../'

  target 'OperatorExtensions_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
